version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: make deps
      - run: 
          name: Run linter
          command: make lint
      - run: 
          name: Run tests
          command: make test
      - run: 
          name: Build Docker image
          command: make docker_build
      - run: 
          name: Push Docker image to Docker Hub
          command: make docker_push # <--- KROK 2: To dodajemy na samym końcu

workflows:
  basic:
    jobs:
      - build-and-test