version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: make deps
      - run: 
          name: Run linter
          command: make lint
      - run: 
          name: Run tests
          command: make test
      - run: 
          name: Build Docker image
          command: make docker_build

workflows:
  basic:
    jobs:
      - build-and-test